// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQsduaUDOAeKDaMhVPnnrF4qV0Rz81j8M',
    appId: '1:696871615793:web:50a7b9a1c56b87a61d0410',
    messagingSenderId: '696871615793',
    projectId: 'visionvault-78559',
    authDomain: 'visionvault-78559.firebaseapp.com',
    storageBucket: 'visionvault-78559.appspot.com',
    measurementId: 'G-QVSHJ5V78R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6yVgn991n5KQCMkYcQvAqIBszxYVgm0',
    appId: '1:696871615793:android:ffb62625f2fadae61d0410',
    messagingSenderId: '696871615793',
    projectId: 'visionvault-78559',
    storageBucket: 'visionvault-78559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWLQU5DscWOLknm4Ld69F576aqFA6-eI',
    appId: '1:696871615793:ios:6e307de820fccfe61d0410',
    messagingSenderId: '696871615793',
    projectId: 'visionvault-78559',
    storageBucket: 'visionvault-78559.appspot.com',
    iosBundleId: 'com.example.visionvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWLQU5DscWOLknm4Ld69F576aqFA6-eI',
    appId: '1:696871615793:ios:0050db189d3e23a71d0410',
    messagingSenderId: '696871615793',
    projectId: 'visionvault-78559',
    storageBucket: 'visionvault-78559.appspot.com',
    iosBundleId: 'com.example.visionvault.RunnerTests',
  );
}
